name: check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      # - name: Set NPM Variables
      #   run: echo "$PACKAGES_NPMRC" > .npmrc
      #   env:
      #     PACKAGES_NPMRC: ${{ secrets.PACKAGES_NPMRC }}
      - name: Install packages
        run: yarn install
      - name: Linter
        run: yarn lint
      - name: Tests
        run: yarn test
