name: check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install --ignore-engines
      - name: Local Linter
        run: yarn lint
      - name: Tests
        run: yarn test
